import type { Metadata } from 'next';
import { Anton, Inter } from 'next/font/google';
import './globals.css';
import NavBar from '../components/NavBar';

const anton = Anton({
  variable: '--font-heading',
  subsets: ['latin'],
  weight: ['400'],
});

const inter = Inter({
  variable: '--font-body',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${anton.variable} ${inter.variable} font-body flex flex-col min-h-screen`}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
